version: "3"

services:
  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    ports:
      - "9090:9090"
    networks:
      - another-mentor-network
    restart: always

  grafana:
    image: grafana/grafana:11.6.0
    container_name: grafana
    ports:
      - "5000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana:/etc/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-pyroscope-app
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - another-mentor-network
    restart: always

  pyroscope:
    image: pyroscope/pyroscope:0.37.2
    container_name: pyroscope
    ports:
      - "4040:4040"
    volumes:
      - pyroscope_data:/var/lib/pyroscope
      - ./pyroscope/pyroscope.yaml:/etc/pyroscope/config.yaml
    networks:
      - another-mentor-network
    restart: always

tempo:
  image: grafana/tempo:main-a4289d9
  container_name: tempo
  ports:
    - "3200:3200"
    - “4318:4318”
    - "4317:4317"
    - "3201:3201" # Prometheus metrics
  volumes:
    - ./tempo:/etc/tempo
    - tempo_data:/tmp/tempo
  command: ["-config.file=/etc/tempo/tempo.yaml"]
  networks:
    - another-mentor-network
  restart: always

volumes:
  prometheus_data:
  grafana_data:
  pyroscope_data:
  tempo_data:

networks:
  another-mentor-network:
    external: true
