server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317
    # zipkin:
    #   endpoint: 0.0.0.0:9411

compactor:
  compaction:
    block_retention: 48h

ingester:
  max_block_duration: 5m

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo
    pool:
      max_workers: 10
      queue_depth: 1000

metrics:
  prometheus:
    endpoint: 0.0.0.0:3201

search:
  enabled: true

usage_report:
  reporting_enabled: false
