version: "3"

x-user-configs: &pg-config-env
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}
  POSTGRES_USER: ${POSTGRES_USER:-postgres}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
  POSTGRES_DB: ${POSTGRES_DB:-user}
  TZ: Asia/Shanghai

services:
  nginx:
    image: nginx:1.27.4-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user-service
    networks:
      - another-mentor-network
    restart: always

  user-service:
    image: ghcr.io/yeisme/another-mentor-user:latest
    ports:
    #   - "8080:8080"
      - "9091:9090"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      <<: *pg-config-env
    networks:
      - another-mentor-network
    volumes:
      - ./logs:/app/logs
      - ./etc:/app/etc
    restart: always

  postgres:
    image: postgres:17-alpine
    environment:
      <<: *pg-config-env
    volumes:
      - ./user_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - another-mentor-network
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  another-mentor-network:
    driver: bridge

volumes:
  postgres_data:
